#!/bin/sh

# Any subsequent(*) commands which fail will cause the shell script to exit immediately
set -e

# Fix PHP styles
vendor/bin/pint --dirty

# Include changes made by Pint into this commit. Without this line, the style changes
# will stay uncommitted.
git add .
